### PR TITLE
98 tms couch styling

### PR DESCRIPTION
**Pull request by tmikeschu**
Going through and adding adequate styling for anything the user can see.

Would love some feedback @njgheorghita @Sh1pley @riverswb @ski-climb 

screen shot 2017-02-13 at 8 20 42 pm
screen shot 2017-02-13 at 8 41 51 pm
screen shot 2017-02-13 at 8 59 58 pm

### CODE REVIEW

**Comment by ski-climb** [comment]
@tmikeschu Overall this is a huge improvement!  Thanks for putting in the hard hours of design and styling.  Below I'm providing some thoughts/impressions.  Take them with a grain of salt and, in the end I trust your judgement.

What would you think about adding some margin/padding around the main content of the couches index/search results page?  Below image is what it looks like for me.  It feels very... full on the page, like I want to back up 5 feet to look at my computer screen.

Also, when looking at My Travel Reservations, what would you think about losing the 'status' column (since we're not really fully using that feature - don't fully use pending/confirmed/cancelled) and providing the city name instead?  I really like that you have the couch name, but that might not tell the whole story of where a trip goes.  

On that same page, what about making those tiles/boxes/buttons with the couch name and travel dates larger?  Maybe make the info take up 2 times the real estate as compared to the spacing between them?  Just a thought.
screen shot 2017-02-14 at 2 41 37 pm

**Comment by tmikeschu** [comment]
@ski-climb duly noted. I hadn't seen the case where the description is longer. I'll figure out how to make that wrap at an earlier point. Also down to change the status column to city, and change the sizing of the cells to be more dominant. Thanks for the thoughtful review!

**Comment by tmikeschu** [comment]
Closes #98 

I've clicked through all the relevant parts of the UX, and I think we are good enough on styling now (save for upcoming messages feature). 

Main changes: 
* Users can only reserve from the couch listing page, so the search index now has links to those show pages. Specs updated accordingly.

* Add infinite scroll to the search index page, will show 4 full listings at a time
screen shot 2017-02-15 at 11 33 13 am

* Format couch listing page
screen shot 2017-02-15 at 10 32 06 am

* Update reservations index
screen shot 2017-02-15 at 11 34 11 am

Ready for rewiew @ski-climb @njgheorghita @Sh1pley @riverswb

**Review by riverswb — APPROVED** [review]
Looks great!

**Comment by njgheorghita** [comment]
@tmikeschu This is so lovely, thanks so much for tackling heap of styling you flexbox guru.

**Pull request merged**
